In [1]:
import pandas as pd

In [2]:
pip install pandas

Requirement already satisfied: pandas in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("VSTopResults.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [5]:
pip install rdkit

Requirement already satisfied: rdkit in /opt/conda/envs/openmm-env/lib/python3.12/site-packages (2024.3.5)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd 
df = pd.read_excel("VSTopResults.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [7]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

In [9]:
df = pd.read_excel("VSTopResults.xlsx")

In [10]:
df

      H-Bonds  Binding Energy               Compound ID
0           3             0.75   \tCUDAout_CHEMBL415690
1           3            -2.47    \tCUDAout_CHEMBL19612
2           3            -2.59     \tCUDAout_CHEMBL1257
3           3            -2.96      \tCUDAout_CHEMBL609
4           3            -3.18     \tCUDAout_CHEMBL1341
...       ...              ...                      ...
1107        7            -7.81   \tCUDAout_CHEMBL342033
1108        8            -5.57   \tCUDAout_CHEMBL266347
1109        8            -6.27  \tCUDAout_CHEMBL4303154
1110        8            -6.78   \tCUDAout_CHEMBL465208
1111        8            -7.14  \tCUDAout_CHEMBL4303415

[1112 rows x 3 columns]

In [11]:
df.head()

   H-Bonds  Binding Energy              Compound ID
0        3             0.75  \tCUDAout_CHEMBL415690
1        3            -2.47   \tCUDAout_CHEMBL19612
2        3            -2.59    \tCUDAout_CHEMBL1257
3        3            -2.96     \tCUDAout_CHEMBL609
4        3            -3.18    \tCUDAout_CHEMBL1341

In [12]:
df.tail(10)

      H-Bonds  Binding Energy               Compound ID
1102        7            -6.45   \tCUDAout_CHEMBL460031
1103        7            -6.62   \tCUDAout_CHEMBL429910
1104        7            -6.85   \tCUDAout_CHEMBL398412
1105        7            -7.06  \tCUDAout_CHEMBL2158347
1106        7            -7.09   \tCUDAout_CHEMBL245067
1107        7            -7.81   \tCUDAout_CHEMBL342033
1108        8            -5.57   \tCUDAout_CHEMBL266347
1109        8            -6.27  \tCUDAout_CHEMBL4303154
1110        8            -6.78   \tCUDAout_CHEMBL465208
1111        8            -7.14  \tCUDAout_CHEMBL4303415

In [9]:
df.shape

(1112, 3)

In [10]:
df.columns

Index(['H-Bonds', 'Binding Energy ', 'Compound ID'], dtype='object')

In [14]:
print (df.columns[1])

Binding Energy

In [15]:
print (df.columns[2])

Compound ID

In [20]:
print (df.columns[0:3])

Index(['H-Bonds', 'Binding Energy ', 'Compound ID'], dtype='object')

In [13]:
print ('Mean of Binding Energy:' , df[df.columns[-2]].mean())

Mean of Binding Energy: -6.25158273381295

In [14]:
# How many molecules have CHEMBL in their name 
df[df['Compound ID'].str.contains('CHEMBL')]

      H-Bonds  Binding Energy               Compound ID
0           3             0.75   \tCUDAout_CHEMBL415690
1           3            -2.47    \tCUDAout_CHEMBL19612
2           3            -2.59     \tCUDAout_CHEMBL1257
3           3            -2.96      \tCUDAout_CHEMBL609
4           3            -3.18     \tCUDAout_CHEMBL1341
...       ...              ...                      ...
1107        7            -7.81   \tCUDAout_CHEMBL342033
1108        8            -5.57   \tCUDAout_CHEMBL266347
1109        8            -6.27  \tCUDAout_CHEMBL4303154
1110        8            -6.78   \tCUDAout_CHEMBL465208
1111        8            -7.14  \tCUDAout_CHEMBL4303415

[1112 rows x 3 columns]

In [15]:
# How many molecules have CHEMBL in their name 
print(df[df['Compound ID'].str.contains('CHEMBL')].shape[0], 'COMPUNDS HAVE CHEMBL in name')

1112 COMPUNDS HAVE CHEMBL in name

In [16]:
df.loc[df['Compound ID'].str.contains('CHEMBL'),'H-Bonds']

0       3
1       3
2       3
3       3
4       3
       ..
1107    7
1108    8
1109    8
1110    8
1111    8
Name: H-Bonds, Length: 1112, dtype: int64